language: ruby
cache: bundler
rvm:
 - 2.4.0
# uncomment and edit the following line if your project needs to run something other than `rake`:
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
services:
  - postgresql
before_script:
  - psql -c 'create database resource_lock_test;' -U postgres
